name: class4vet
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^1.1.6
  cached_network_image: ^3.3.1
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/icons/category/
    - assets/images/

dependency_overrides:
  file: ^7.0.0
  vector_graphics: ^1.1.9+1