import 'package:class4vet/models/category.dart';
import 'package:flutter/material.dart';

//대분류 - 중분류 - 클래스 - 강의
final List<Category> categories = [
  Category(
    id: '1',
    name: '내과',
    image: 'https://picsum.photos/200/200?random=1',
    subCategories: [
      SubCategory(
        id: '1-1',
        name: '감별진단',
        classes: [
          ClassModel(
            id: '1-1-1',
            name: '구토',
            lectures: [
              Lecture(
                id: '1-1-1-1',
                title: '구토의 기본 원인과 진단',
                description: '구토의 주요 원인과 진단 방법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=2',
                price: '₩50,000',
                review: '4.9',
                duration: '2시간',
                instructor: '김수아 교수',
                level: '초급',
              ),
              Lecture(
                id: '1-1-1-2',
                title: '구토의 치료와 관리',
                description: '구토 환자의 치료와 관리 방법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=3',
                price: '₩60,000',
                review: '4.8',
                duration: '2.5시간',
                instructor: '이민호 교수',
                level: '중급',
              ),
              Lecture(
                id: '1-1-1-3',
                title: '구토 관련 응급상황 대처법',
                description: '구토로 인한 탈수 및 응급상황 발생 시 대처 방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=11',
                price: '₩65,000',
                review: '4.7',
                duration: '3시간',
                instructor: '정현우 교수',
                level: '고급',
              ),
            ],
          ),
          ClassModel(
            id: '1-1-2',
            name: '설사',
            lectures: [
              Lecture(
                id: '1-1-2-1',
                title: '설사의 원인과 진단',
                description: '설사의 주요 원인과 진단 방법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=4',
                price: '₩45,000',
                review: '4.7',
                duration: '1.5시간',
                instructor: '박지원 교수',
                level: '초급',
              ),
              Lecture(
                id: '1-1-2-2',
                title: '설사의 치료 프로토콜',
                description: '다양한 원인에 따른 설사 치료 프로토콜을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=12',
                price: '₩55,000',
                review: '4.8',
                duration: '2시간',
                instructor: '이지은 교수',
                level: '중급',
              ),
            ],
          ),
          ClassModel(
            id: '1-1-3',
            name: '식욕부진',
            lectures: [
              Lecture(
                id: '1-1-3-1',
                title: '식욕부진의 감별진단',
                description: '식욕부진의 다양한 원인과 진단법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=13',
                price: '₩50,000',
                review: '4.6',
                duration: '2시간',
                instructor: '강민석 교수',
                level: '초급',
              ),
              Lecture(
                id: '1-1-3-2',
                title: '식욕부진 환자 관리',
                description: '식욕부진 환자의 영양 관리와 치료 방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=14',
                price: '₩55,000',
                review: '4.7',
                duration: '2.5시간',
                instructor: '김지민 교수',
                level: '중급',
              ),
            ],
          ),
        ],
      ),
      SubCategory(
        id: '1-2',
        name: '약처방',
        classes: [
          ClassModel(
            id: '1-2-1',
            name: '항생제',
            lectures: [
              Lecture(
                id: '1-2-1-1',
                title: '항생제의 기본 원리',
                description: '항생제의 작용 원리와 선택 기준에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=5',
                price: '₩55,000',
                review: '4.8',
                duration: '2시간',
                instructor: '최영식 교수',
                level: '중급',
              ),
              Lecture(
                id: '1-2-1-2',
                title: '항생제 내성과 대안적 치료',
                description: '항생제 내성의 발생 원인과 대안적 치료법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=15',
                price: '₩65,000',
                review: '4.9',
                duration: '3시간',
                instructor: '박준호 교수',
                level: '고급',
              ),
            ],
          ),
          ClassModel(
            id: '1-2-2',
            name: '진통제',
            lectures: [
              Lecture(
                id: '1-2-2-1',
                title: '동물용 진통제의 종류와 적용',
                description: '다양한 진통제의 종류와 적절한 적용 방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=16',
                price: '₩50,000',
                review: '4.8',
                duration: '2시간',
                instructor: '김태우 교수',
                level: '초급',
              ),
              Lecture(
                id: '1-2-2-2',
                title: '만성 통증 관리',
                description: '노령 동물의 만성 통증 관리에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=17',
                price: '₩60,000',
                review: '4.7',
                duration: '2.5시간',
                instructor: '이서현 교수',
                level: '중급',
              ),
            ],
          ),
        ],
      ),
      SubCategory(
        id: '1-3',
        name: '영양학',
        classes: [
          ClassModel(
            id: '1-3-1',
            name: '기초 영양학',
            lectures: [
              Lecture(
                id: '1-3-1-1',
                title: '반려동물 영양소 요구량',
                description: '강아지와 고양이의 기본 영양소 요구량에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=18',
                price: '₩45,000',
                review: '4.6',
                duration: '2시간',
                instructor: '정수민 교수',
                level: '초급',
              ),
            ],
          ),
          ClassModel(
            id: '1-3-2',
            name: '질병별 식이요법',
            lectures: [
              Lecture(
                id: '1-3-2-1',
                title: '신장질환 식이요법',
                description: '신장질환 환자를 위한 식이요법과 영양 관리를 학습합니다.',
                image: 'https://picsum.photos/200/200?random=19',
                price: '₩55,000',
                review: '4.8',
                duration: '2.5시간',
                instructor: '김현우 교수',
                level: '중급',
              ),
              Lecture(
                id: '1-3-2-2',
                title: '당뇨병 식이요법',
                description: '당뇨병 환자를 위한 식이요법과 혈당 관리를 학습합니다.',
                image: 'https://picsum.photos/200/200?random=20',
                price: '₩55,000',
                review: '4.7',
                duration: '2시간',
                instructor: '이민지 교수',
                level: '중급',
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  Category(
    id: '2',
    name: '외과',
    image: 'https://picsum.photos/200/200?random=6',
    subCategories: [
      SubCategory(
        id: '2-1',
        name: '수술 기법',
        classes: [
          ClassModel(
            id: '2-1-1',
            name: '기본 수술',
            lectures: [
              Lecture(
                id: '2-1-1-1',
                title: '기본 수술 기법',
                description: '기본적인 수술 기법과 주의사항에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=7',
                price: '₩70,000',
                review: '4.9',
                duration: '3시간',
                instructor: '정민우 교수',
                level: '중급',
              ),
              Lecture(
                id: '2-1-1-2',
                title: '봉합 기법의 이해',
                description: '다양한 봉합 기법과 적용 방법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=21',
                price: '₩60,000',
                review: '4.8',
                duration: '2.5시간',
                instructor: '박성호 교수',
                level: '초급',
              ),
            ],
          ),
          ClassModel(
            id: '2-1-2',
            name: '정형외과',
            lectures: [
              Lecture(
                id: '2-1-2-1',
                title: '골절 치료의 기본',
                description: '다양한 골절 유형과 치료 방법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=22',
                price: '₩75,000',
                review: '4.9',
                duration: '3.5시간',
                instructor: '이준영 교수',
                level: '중급',
              ),
              Lecture(
                id: '2-1-2-2',
                title: '고관절 질환 수술',
                description: '고관절 이형성증과 관련 수술 기법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=23',
                price: '₩80,000',
                review: '4.8',
                duration: '4시간',
                instructor: '김동현 교수',
                level: '고급',
              ),
            ],
          ),
        ],
      ),
      SubCategory(
        id: '2-2',
        name: '마취학',
        classes: [
          ClassModel(
            id: '2-2-1',
            name: '기본 마취',
            lectures: [
              Lecture(
                id: '2-2-1-1',
                title: '수의 마취의 기본 원리',
                description: '동물 마취의 기본 원리와 약물에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=24',
                price: '₩65,000',
                review: '4.7',
                duration: '2.5시간',
                instructor: '정원석 교수',
                level: '초급',
              ),
              Lecture(
                id: '2-2-1-2',
                title: '국소 마취 기법',
                description: '다양한 국소 마취 기법과 적용 방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=25',
                price: '₩60,000',
                review: '4.6',
                duration: '2시간',
                instructor: '박지영 교수',
                level: '중급',
              ),
            ],
          ),
          ClassModel(
            id: '2-2-2',
            name: '응급 마취',
            lectures: [
              Lecture(
                id: '2-2-2-1',
                title: '응급 상황에서의 마취 관리',
                description: '외상 환자 및 응급 상황에서의 마취 관리법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=26',
                price: '₩70,000',
                review: '4.8',
                duration: '3시간',
                instructor: '이지훈 교수',
                level: '고급',
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  Category(
    id: '3',
    name: '영상학과',
    image: 'https://picsum.photos/200/200?random=8',
    subCategories: [
      SubCategory(
        id: '3-1',
        name: '초음파',
        classes: [
          ClassModel(
            id: '3-1-1',
            name: '복부 초음파',
            lectures: [
              Lecture(
                id: '3-1-1-1',
                title: '복부 초음파 기초',
                description: '복부 초음파의 기본 원리와 해석 방법에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=9',
                price: '₩65,000',
                review: '4.8',
                duration: '2.5시간',
                instructor: '김지수 교수',
                level: '초급',
              ),
              Lecture(
                id: '3-1-1-2',
                title: '간 및 담도계 초음파',
                description: '간 및 담도계 질환의 초음파 진단법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=27',
                price: '₩70,000',
                review: '4.9',
                duration: '3시간',
                instructor: '박세진 교수',
                level: '중급',
              ),
            ],
          ),
          ClassModel(
            id: '3-1-2',
            name: '심장 초음파',
            lectures: [
              Lecture(
                id: '3-1-2-1',
                title: '심장 초음파 기본',
                description: '심장 초음파의 기본 원리와 촬영 방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=28',
                price: '₩75,000',
                review: '4.8',
                duration: '3시간',
                instructor: '이한솔 교수',
                level: '중급',
              ),
              Lecture(
                id: '3-1-2-2',
                title: '심장 질환의 초음파 진단',
                description: '다양한 심장 질환의 초음파 진단 방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=29',
                price: '₩80,000',
                review: '4.9',
                duration: '3.5시간',
                instructor: '정승원 교수',
                level: '고급',
              ),
            ],
          ),
        ],
      ),
      SubCategory(
        id: '3-2',
        name: 'X-ray',
        classes: [
          ClassModel(
            id: '3-2-1',
            name: '흉부 X-ray',
            lectures: [
              Lecture(
                id: '3-2-1-1',
                title: '흉부 X-ray 판독 기초',
                description: '흉부 X-ray 촬영법과 기본 판독법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=30',
                price: '₩60,000',
                review: '4.7',
                duration: '2.5시간',
                instructor: '김태윤 교수',
                level: '초급',
              ),
              Lecture(
                id: '3-2-1-2',
                title: '폐 질환 X-ray 판독',
                description: '다양한 폐 질환의 X-ray 소견과 판독법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=31',
                price: '₩65,000',
                review: '4.8',
                duration: '3시간',
                instructor: '박민준 교수',
                level: '중급',
              ),
            ],
          ),
          ClassModel(
            id: '3-2-2',
            name: '정형외과 X-ray',
            lectures: [
              Lecture(
                id: '3-2-2-1',
                title: '골절 X-ray 판독',
                description: '다양한 골절 유형의 X-ray 판독법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=32',
                price: '₩65,000',
                review: '4.8',
                duration: '3시간',
                instructor: '정민석 교수',
                level: '중급',
              ),
            ],
          ),
        ],
      ),
      SubCategory(
        id: '3-3',
        name: 'CT/MRI',
        classes: [
          ClassModel(
            id: '3-3-1',
            name: 'CT 기초',
            lectures: [
              Lecture(
                id: '3-3-1-1',
                title: 'CT의 원리와 적용',
                description: 'CT 검사의 원리와 임상 적용에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=33',
                price: '₩75,000',
                review: '4.8',
                duration: '3시간',
                instructor: '이준호 교수',
                level: '중급',
              ),
            ],
          ),
          ClassModel(
            id: '3-3-2',
            name: 'MRI 기초',
            lectures: [
              Lecture(
                id: '3-3-2-1',
                title: 'MRI의 원리와 적용',
                description: 'MRI 검사의 원리와 임상 적용에 대해 학습합니다.',
                image: 'https://picsum.photos/200/200?random=34',
                price: '₩80,000',
                review: '4.9',
                duration: '3.5시간',
                instructor: '김서연 교수',
                level: '중급',
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  Category(
    id: '4',
    name: '피부과',
    image: 'https://picsum.photos/200/200?random=35',
    subCategories: [
      SubCategory(
        id: '4-1',
        name: '알러지',
        classes: [
          ClassModel(
            id: '4-1-1',
            name: '알러지성 피부염',
            lectures: [
              Lecture(
                id: '4-1-1-1',
                title: '알러지성 피부염의 진단',
                description: '알러지성 피부염의 원인과 진단 방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=36',
                price: '₩60,000',
                review: '4.7',
                duration: '2.5시간',
                instructor: '박소현 교수',
                level: '초급',
              ),
              Lecture(
                id: '4-1-1-2',
                title: '알러지성 피부염의 치료',
                description: '알러지성 피부염의 다양한 치료법과 관리법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=37',
                price: '₩65,000',
                review: '4.8',
                duration: '3시간',
                instructor: '김민지 교수',
                level: '중급',
              ),
            ],
          ),
        ],
      ),
      SubCategory(
        id: '4-2',
        name: '감염성 질환',
        classes: [
          ClassModel(
            id: '4-2-1',
            name: '세균성 피부감염',
            lectures: [
              Lecture(
                id: '4-2-1-1',
                title: '세균성 피부감염의 진단과 치료',
                description: '다양한 세균성 피부감염의 진단과 치료법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=38',
                price: '₩65,000',
                review: '4.8',
                duration: '3시간',
                instructor: '이승준 교수',
                level: '중급',
              ),
            ],
          ),
          ClassModel(
            id: '4-2-2',
            name: '진균성 피부감염',
            lectures: [
              Lecture(
                id: '4-2-2-1',
                title: '피부 진균증의 진단',
                description: '피부 진균증의 임상적 특징과 진단법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=39',
                price: '₩60,000',
                review: '4.7',
                duration: '2.5시간',
                instructor: '정유진 교수',
                level: '초급',
              ),
              Lecture(
                id: '4-2-2-2',
                title: '피부 진균증의 치료',
                description: '다양한 피부 진균증의 치료법과 예방법을 학습합니다.',
                image: 'https://picsum.photos/200/200?random=40',
                price: '₩65,000',
                review: '4.8',
                duration: '3시간',
                instructor: '김지원 교수',
                level: '중급',
              ),
            ],
          ),
        ],
      ),
    ],
  ),
];

final Map<String, String> profile = {
  "name": "김수아",
  "image": "https://picsum.photos/200/200?random=10",
  "email": "kim.sua@example.com",
  "phone": "010-1234-5678",
  "address": "서울시 강남구",
  "bio": "수의사, 내과 전문의",
};

final List<Map<String, dynamic>> chatInfo = [
  {
    'id': '1',
    'name': '강원석 교수',
    'image': 'https://picsum.photos/200/200?random=41',
    'role': '내과 전문의',
    'lastMessage': '안녕하세요! 강의에 관해 궁금한 점이 있으시면 언제든 물어보세요.',
    'time': '오전 10:30',
  },
  {
    'id': '2',
    'name': '이지연 교수',
    'image': 'https://picsum.photos/200/200?random=42',
    'role': '외과 전문의',
    'lastMessage': '수술 실습 일정이 변경되었습니다. 확인 부탁드립니다.',
    'time': '오전 11:45',
  },
  {
    'id': '3',
    'name': '박준영 교수',
    'image': 'https://picsum.photos/200/200?random=43',
    'role': '영상학과 전문의',
    'lastMessage': 'X-ray 판독 과제 제출 기한을 확인해주세요.',
    'time': '오후 2:15',
  },
  {
    'id': '4',
    'name': '김서연 교수',
    'image': 'https://picsum.photos/200/200?random=44',
    'role': '피부과 전문의',
    'lastMessage': '피부 진균증 관련 질문 감사합니다. 답변 드렸어요.',
    'time': '오후 3:30',
  },
];
