name: Deploy Flutter Web to aws

on:
  push:
    branches: [stg]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy to S3
        run: |
          aws s3 sync ./build/web s3://${{ vars.S3_BUCKET }} --delete
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
